server:
	host: 	localhost    
	port:   2007 2009 5456     
	max_body_size: 10000000   
	root: /Users/abouabra/1337/backserve/assets/server_1//site  gfhfgh
	server_name: ghjfghjfhj fghfgh
	index: index.html  
	error_pages:   
		400: error_pages/400.html
		403: error_pages/403.html fghh
		404: error_pages/404.html	
		405: error_pages/405.html
		410: error_pages/413.html
	location: /site_1/
		index: index.html  
		methods: POST             GET     DELETE      
	location: /site_1/lsls/1/
		methods: POST             GET     DELETE      
		index: index.html

	location: /site_2/
		index: index.html

	location: /to_server_2/
		redirect_URL: http://0.0.0.0:2004/sdf
	
	location: /to_server_3/
		redirect_URL: http://0.0.0.0:2005/ 

	location: /list/
		directory_listing: true
		methods: GET


server:
	host: localhost   
	port:   2006 7056 6666
	root: /Users/abouabra/1337/backserve/assets/server_1/
	max_body_size: 1000000    
	server_name: firstserver dsdsd   

	index: index.html
	error_pages:       
		400: error_pages/400.html
		403: error_pages/403.html fgdfgdfgf
		404: error_pages/404.html
		405: error_pages/405.html
		410: error_pages/413.html
	location: /site_1/
	root: /Users/abouabra/1337/backserve/assets/server_1/
		index: index.html

	location: /site_1/lsls/1  /
		methods: POST  GET 
		index: index.html

	location: /site_2/
		index: index.html 
		alias: /ok/

	location: /to_server_2/
		redirect_URL:      http://0.0.0.0:2004/         

	location: /to_server_3/
		redirect_URL: http://0.0.0.0:2005/

	location: /list/
		directory_listing: true   
		methods: GET   