#############################################
#										                        #
#		   THE DEFAULT CONFIGURATION FILE		    #
#										                        #
#############################################

server:
	host: 0.0.0.0
	port: 2001
	root: /Users/rarraji/Desktop/prj/WebServMerge/pages/ErrorPages
	max_body_size: 1000000 # 1MB

	# Index Page
	index: index.html

	# Error Pages
	error_pages:
		400: error_pages/400.html
		403: error_pages/403.html
		404: error_pages/404.html
		405: error_pages/405.html
		413: error_pages/413.html
   
    # Location Blocks
	location: /
	# 	index: /Solix.py
	# 	methods: GET | POST

	location: /ErrorPages/
		directory_listing: true
		methods: GET | DELETE

	location: /web1/
		index: /index.html
		methods: DELETE | POST

	location: /site_2/
		redirect_URL: /
		index: /index.html

server:
	host: 0.0.0.0
	port: 2002
	root: /Users/rarraji/Desktop/prj/WebServMerge/pages
	max_body_size: 1000000 # 1MB

	# Index Page
	index: index.html

	# Error Pages
	error_pages:
		400: error_pages/400.html
		403: error_pages/403.html
		404: error_pages/404.html
		405: error_pages/405.html
		413: error_pages/413.html
   
    # Location Blocks
	location: /
		index: /index.html
		methods: GET | POST

	location: /ErrorPages/
		directory_listing: true
		methods: GET | DELETE

	location: /web1/
		index: /index.html
		methods: DELETE | POST

	location: /site_2/
		redirect_URL: /
		index: /index.html

server:
	host: 0.0.0.0
	port: 2003
	root: /Users/rarraji/Desktop/lastWeb/Server/pages/
	max_body_size: 1000000 # 1MB

	index: main.py

	error_pages:
		400: error_pages/400.html
		403: error_pages/403.html
		404: error_pages/404.html
		500: error_pages/500.html
		502: error_pages/502.html
		504: error_pages/504.html


	location: /
		root: /Users/rarraji/1337/backserve/assets/server_3/home/
		index: home.py
		methods: GET

	location: /login
		index: login.py
		methods: GET | POST

	location: /logout
		index: logout.py
		methods: GET
	
	location: /switch
		index: switch.py
		methods: GET
	